### ISSUE TITLE
Discrepancy between code and doc for sigmoid

### ISSUE THREAD

**Issue by shinh** [belltailjp/chainer_computational_cost#17]
https://github.com/belltailjp/chainer_computational_cost/blob/master/DETAILS.md#sigmoid

says flops of sigmoid is `4*x` but

https://github.com/belltailjp/chainer_computational_cost/blob/master/chainer_computational_cost/cost_calculators/activation.py#L87

returns `x.size` (not `4 * x.size`)?

**Comment by belltailjp** [comment]
Oops, thanks so much for pointing that out! I thinks thats a bug and should be fixed!
